meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneui/recipes-luneui/luna-next/luna-next.bb, meta-luneui/recipes-qt/qt5/qtwayland_git.bbappend
These 2 should solve most of the Luna-Next-Cardshell restarts.
=> 2 forgotten SRCREV updates (the most critical ones actually)

meta-luneos/recipes-luneos/webos-keyboard/webos-keyboard.bb
To fix behavior of Ajax input in Maps and websites.
=> webos-keyboard: Bump SRCREV

meta-luneos/recipes-qt/qt5/qtbase_git.bbappend
=> qtbase: fix font path mismatch with fontconfig

meta-luneos/recipes-qt/qt5/qtbase_git.bbappend
=> qtbase: fix font path in FILES_${PN}-fonts

meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
=> qtwebengine: fix chromium srcrev dependency for build

meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
Reverts webOS-ports/meta-webos-ports#154
=> Revert 10c1cfbdb549a0cfc5e6c32a867ac72acd13a8a6

meta-luneos/recipes-qt/qt5/qtlocation/0001-Implement-stub-luneos-plugin-based-on-location-servi.patch, meta-luneos/recipes-qt/qt5/qtlocation_git.bbappend
Signed-off-by: Nikolay Nizov <nizovn@gmail.com>
=> qtlocation: implement LuneOS positioning plugin

meta-luneos/recipes-luneos/cardshell/luna-next-cardshell.bb, meta-luneos/recipes-luneos/luneos-components/luneos-components.bb
luna-next-cardshell:
33ddd2c Further work on bluetooth submenu of SystemMenu
luneos-components:
44f5683 Add stub org.nemomobile.dbus module
Signed-off-by: Nikolay Nizov <nizovn@gmail.com>
=> luna-next-cardshell,luneos-components: bump SRCREV

meta-luneos/conf/distro/include/luneos.inc
=> Distro: set GStreamer 1.0 to be used by QtMultimedia

meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
=> Fix extra codecs build

meta-luneos/recipes-webos/sleepd/sleepd.bb
To solved http://issues.webos-ports.org/issues/461
=> Add installation of alarms.xml

meta-luneos/recipes-luneos/apps/org.webosports.app.phone.bb
=> org.webosports.app.phone: inherit from webos_application

meta-luneos/recipes-nemomobile/voicecall/voicecall/0002-WaitfortheofonoVoiceCalltobevalidbeforeaddingit.patch, meta-luneos/recipes-nemomobile/voicecall/voicecall_git.bb
=> voicecall: add a patch to fix handling of OfonoVoiceCall initialization

meta-luneos/recipes-webos/frameworks/loadable-frameworks.bb
=> loadable-frameworks: add phonenumberlib framework

meta-luneos/recipes-core/libhybris/libhybris_git.bbappend
=> libhybris: bump SRCREV to latest

meta-luneos/recipes-qt/qt5/qtscenegraph-adaptation/0002-Fix-createTexture-API-for-Qt5-6.patch, meta-luneos/recipes-qt/qt5/qtscenegraph-adaptation_git.bb
=> qtscenegraph-adaptation: fix Qt 5.6 API for createTexture

meta-luneos/recipes-graphics/wayland/wayland_1.9.0.bb
=> wayland: overload recipe of oe-core with version 1.9.0

meta-luneos/classes/remove-libtool.bbclass, meta-luneos/conf/layer.conf
=> Add commits required for QT 5.6

meta-luneos/recipes-luneos/services/downloadmanager.bb
add rewrite of download manager to LuneOS.
=> org.webosports.service.downloadmgr: initial recipe

meta-luneos/classes/webos_enyodev_application.bbclass, meta-luneos/recipes-support/nodejs-enyo-dev/nodejs-enyo-dev.bb
Signed-off-by: Alan Stice <alan@alanstice.com>
=> Working Enyo 2.7 recipes

meta-luneos/recipes-luneos/services/imaccountvalidator.bb, meta-luneos/recipes-luneos/services/imlibpurpleservice.bb, meta-luneos/recipes-support/freeimage/freeimage/0001-dsp-mips-add-whitespace-around-stringizing-operator.patch, meta-luneos/recipes-support/freeimage/freeimage_3.17.0.bb, meta-luneos/recipes-support/pidgin/pidgin-sipe_1.21.1.bb, meta-luneos/recipes-support/pidgin/pidgin_2.10.12.bbappend, meta-luneos/recipes-support/pidgin/whatsapp-purple.bb
=> Add libpurple plugins for SIPE & WhatsApp & deploy them with other plugins

meta-luneos/recipes-support/pidgin/purple-skypeweb_git.bb
=> purple-skypeweb: bump SRCREV to 1.2

meta-luneos/recipes-devtools/binutils/binutils/0015-allow-zero-length-elements.patch, meta-luneos/recipes-devtools/binutils/binutils_2.26.bbappend
=> binutils: fix issue with ipks containing empty items

meta-luneos/recipes-luneos/services/org.webosinternals.ipkgservice.bb
Open-WebOS-DCO-1.0-Signed-Off-By: Doug Reeder reeder.29@gmail.com
=> Preware 2 uses secure feeds, where available. 

meta-luneos/recipes-qt/qt5/qtquickcontrols/0001-Set-a-transparent-background-for-contextual-menus.patch, meta-luneos/recipes-qt/qt5/qtquickcontrols_git.bbappend
=> qtquickcontrols: transparent background for contextual menus

meta-luneos/recipes-luneos/luneos-components/luneos-components.bb
=> luneos-components: add LunaWebEngineViewStyle/ in package

meta-luneos/recipes-core/images/luneos-emulator-appliance/luneos-emulator.ovf, meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb
=> qemux86: Fix serial ports & add phone infrastructure

meta-luneos/recipes-luneos/webos-systemd-services/webos-systemd-services.bb, meta-luneos/recipes-webos/luna-sysmgr/luna-sysmgr.bb
-So we can install systemd service file from it
-Move db kind files to more generic location
-Add com.palm.contextupload for collecting error logs
=> Cleanup luna-sysmgr recipe

.gitignore, meta-luneos/recipes-luneos/services/org.webosinternals.ipkgservice.bb
Open-WebOS-DCO-1.0-Signed-Off-By: Doug Reeder <reeder.29@gmail.com>
=> Updates Preware feed for FeedSpider to secure URL.

meta-luneos/recipes-core/libhybris/libhybris_git.bbappend, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid/0004-Dont-include-QCOM_HARDWARE-related-defines.patch, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid_git.bb, meta-luneos/recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0003-Fix-4_4_2_hwcomposer_v0_build.patch, meta-luneos/recipes-qt/qt5/qt5-qpa-hwcomposer-plugin_git.bb
Please don't merge this before discussing it with me, as it is tightly related to other PRs.
=> Use Android HAL overlay and migrate mako to cm12.1

meta-luneos/recipes-connectivity/mobile-broadband-provider-info/mobile-broadband-provider-info_git.bbappend
=> mobile-broadband-provider-info: fix QA error

meta-luneos/recipes-core/libhybris/libhybris_git.bbappend
=> libhybris: bump SRCREV

meta-luneos/recipes-core/libhybris/libhybris/0001-hooks-include-mm-hooks-only-when-WANT_LINKER_MM-is-d.patch, meta-luneos/recipes-core/libhybris/libhybris/0002-hooks-fix-crash-with-__get_tls_hooks.patch, meta-luneos/recipes-core/libhybris/libhybris_git.bbappend
=> libhybris: Bump SRCREV, together with fixes for issues

meta-luneos/recipes-multimedia/exiv2/exiv2_0.25.bb, meta-luneos/recipes-multimedia/qtubuntu-camera/libqtubuntu-media-signals_bzr.bb, meta-luneos/recipes-multimedia/qtubuntu-camera/qtubuntu-camera_bzr.bb
These recipes are not yet used nor included in our builds; but following morphis' idea, I think
it will be a good candidate for a future camera functionality.
=> Add qtubuntu-camera as backend

meta-luneos/recipes-multimedia/qtubuntu-camera/qtvideo-node_bzr.bb
=> qtubuntu-camera: add qtvideo-node for VideoOutput plugin

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-luneos/apps/org.webosports.app.camera.bb, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio_8.0.bbappend, meta-luneos/recipes-multimedia/qtubuntu-camera/libqtubuntu-media-signals_bzr.bb, meta-luneos/recipes-multimedia/qtubuntu-camera/qtubuntu-camera_bzr.bb
Do not merge this as long as:
- https://github.com/shr-distribution/meta-smartphone/pull/22 isn't merged
- https://github.com/webOS-ports/org.webosports.app.camera doesn't exist
I will also test this at home before it gets merged here.
=> Add org.webosports.app.camera and the camera infrastructure packages

meta-luneos/recipes-luneos/apps/org.webosports.app.camera.bb
=> org.webosports.app.camera: fix package

meta-luneos/recipes-luneos/apps/org.webosports.app.camera.bb
=> org.webosports.app.camera: bump SRCREV

meta-luneos/recipes-luneos/apps/org.webosports.app.camera.bb, meta-luneos/recipes-multimedia/qtubuntu-camera/qtubuntu-camera_bzr.bb, meta-luneos/recipes-multimedia/qtubuntu-camera/qtvideo-node_bzr.bb
=> qtubuntu-camera: add missing dependencies for Qt

meta-luneos/recipes-connectivity/ofono/ofono-conf/environment.conf, meta-luneos/recipes-connectivity/ofono/ofono_1.19.bbappend
=> Use Mer's oFono 1.19 and include fix

meta-luneos/recipes-qt/qt5/qtsensors_git.bbappend
=> qtsensors: correct path for sensors config file

meta-luneos/recipes-luneos/luneos-components/luneos-components.bb
=> luneos-components: add QtQuickControls2 support

meta-luneos/recipes-luneos/luneos-components/luneos-components.bb
Also, fix FILES to reference LuneOS instead of LuneOSStyle
=> luneos-components: bump SRCREV

meta-luneui/recipes-qt/qt5/qtwebengine/chromium/0013-Fix-build-error-in-WindowFeaturesStructTraits.patch, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
=> qtwebengine: Fix build error

meta-luneui/recipes-qt/qt5/qtwebengine/0016-Fix_GetDefaultScreenInfo.patch, meta-luneui/recipes-qt/qt5/qtwebengine/0017-Fix_Missing_targetUrl.patch, meta-luneui/recipes-qt/qt5/qtwebengine/chromium/0014-Fix_webos_module.patch, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
This should get us to a complete build of qtwebengine.
However, the getter for onservicecallback IDL attribute
is not satisfying! (always return null)
=> qtwebengine: additionnal fixes

meta-luneui/recipes-qt/qt5/qtwebengine/0018-Revert-Load-libEGL-and-libGLES2-symbols-implicitly.patch, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
=> qtwebengine: fix loading of libEGL & libGLES

meta-luneui/recipes-qt/qt5/qtwayland/0002-QWaylandWindow-reset-window-should-reset-mask.patch
=> qtwayland: fix mask patch

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-multimedia/qtubuntu-camera/qtubuntu-camera_bzr.bb
=> qtubuntu-camera: fix and re-enable camera related recipes

meta-luneui/recipes-qt/qt5/qtwebengine/0019-Add-LuneOS-specific-switches.patch, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
=> qtwebengine: add LuneOS specific switches

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/mako/webos-system.pa
=> mako: avoid loading conflicting Alsa driver

meta-luneos/recipes-connectivity/mobile-broadband-provider-info/mobile-broadband-provider-info_git.bbappend, meta-luneos/recipes-connectivity/ofono/ofono_%.bbappend, meta-luneos/recipes-nemomobile/voicecall/voicecall/0001-Adapt-thingstoworkinLuneOS.patch, meta-luneos/recipes-nemomobile/voicecall/voicecall_git.bb, meta-luneos/recipes-support/nemo-qml-plugin-dbus/nemo-qml-plugin-dbus_git.bb
Since we're anyway doing ConnMan, BlueZ, we can just as well do oFono & VoiceCall too. 
=> Update our telephony bits as well

meta-luneos/recipes-webos/luna-init/luna-init.bb, meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf.bb, meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf/defaultPreferences-platform.txt, meta-luneos/recipes-webos/luna-sysmgr/luna-sysmgr.bb
=> luna-sysmgr-conf, luna-init: Fix minor issues

meta-luneos/recipes-connectivity/bluez5/bluez5/0001-Case-insensitive-firmware-name.patch, meta-luneos/recipes-connectivity/bluez5/bluez5_%.bbappend
=> bluez5: make firmware search case insensitive

meta-luneos/recipes-luneos/apps/org.webosports.app.settings-qml.bb
-And bump SRCREV for the newly added apps.
=> org.webosports.app.settings-qml: Add all possible apps to recipe

meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf/mido/luna-platform.conf, meta-luneos/recipes-webos/nyx-conf/nyx-conf/mido/nyx.conf, meta-luneos/recipes-webos/nyx-modules/nyx-modules/mido.cmake, meta-luneui/recipes-luneui/luna-next/luna-next-conf/mido/environment.conf
=> mido: Initial configuration files

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb
=> packagegroup-luneos-extended: Add WIP targets and more documentation

meta-luneos/recipes-android/android-tools/android-tools-conf/0001_Enable_FunctionFS.install_patch, meta-luneos/recipes-android/android-tools/android-tools-conf_1.0.bbappend, meta-luneos/recipes-android/android-tools/android-tools/0001-Allow-adbd-to-be-ran-as-root.patch, meta-luneos/recipes-android/android-tools/android-tools_5.1.1.r37.bbappend
Also improve the android-gadget-setup to handle devices with
FunctionFS enables (like "mido" device).
=> android-tools: fix compatibility with adb 5.1.1

meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf/athene/luna-platform.conf, meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf/onyx/luna-platform.conf, meta-luneos/recipes-webos/nyx-modules/nyx-modules/athene.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/onyx.cmake
So build will succeed at least.
=> Add initial luna-sysmgr-conf and nyx-modules for athene and onyx

meta-luneui/recipes-qt/qt5/qtbase/0002-Temporary-fix-for-SIGBUS-crash-disable-TLS.patch, meta-luneui/recipes-qt/qt5/qtbase_git.bbappend
=> qtbase: temporary fix for SIGBUS crash on Android devices

meta-luneos/recipes-android/android-tools/android-tools-conf/0001_Enable_FunctionFS.install_patch, meta-luneos/recipes-android/android-tools/android-tools/android-tools-adbd.service
=> android-gadget-setup: fix functionfs test

meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf/rosy/luna-platform.conf, meta-luneos/recipes-webos/nyx-modules/nyx-modules/rosy.cmake
=> luna-sysmgr-conf, nyx-modules: fix rosy values

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/tissot/webos-system.pa, meta-luneos/recipes-webos/nyx-modules/nyx-modules/mido.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/tissot.cmake
=> Fix some issues for Tissot & Mido

meta-luneos/recipes-webos/nyx-conf/nyx-conf/onyx/nyx.conf
Signed-off-by: Ian Miller <git@och.me.uk>
=> onyx: Enable power button

meta-luneos/recipes-webos/nyx-modules/nyx-modules/rosy.cmake
=> nyx-modules: fix rosy's cmake

.gitignore
=> Ignore generated pycache directory

meta-luneos/recipes-core/systemd/systemd_%.bbappend
=> systemd: fix build without resolved

meta-luneos/conf/distro/include/defaulttunes.inc
Local build still running, don't merge yet.
=> WIP, use different TUNE_PKGARCH for raspberryip3-64

meta-luneos/recipes-nemomobile/voicecall/voicecall/0001-Adapt-thingstoworkinLuneOS.patch, meta-luneos/recipes-nemomobile/voicecall/voicecall_git.bb
Some minor updates upstream, update patches as well.
=> voicecall: Bump version to latest from upstream and refresh patches

meta-luneui/recipes-webos/luna-sysmgr-common/luna-sysmgr-common.bb
=> luna-sysmgr-common: Bump SRCREV

meta-luneos/recipes-core/images/luneos-package.inc
* Fix for reset of firstboot flag
=> luneos-package.inc: bump android-update-package SRCREV

meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-sysbus.bb
This partially reverts commit d1ea8d778a4dc9a8195ff747531795284c2ea783,
and also bumps SRCREV to add an important fix.
=> nodejs-module-webos-sysbus: restore old security schema

meta-luneos/recipes-core/initscripts/webos-initscripts.bb
=> webos-initscripts: Fix whitespace issues

meta-luneos/recipes-graphics/sdl2-opengles-test/sdl2-opengles-test_git.bb, meta-luneos/recipes-qt/qt5/qtlocation-luneos-plugin_git.bb
=> sdl2-opengles-test, qtlocation-luneos-plugin: Fix minor build issues.

meta-luneos/recipes-luneos/luna-webappmanager/luna-webappmanager.bb
=> luna-webappmanager: bump SRCREV

meta-luneos-backports-2.8/recipes-graphics/mesa/files/0001-Allow-enable-DRI-without-DRI-drivers.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/files/0001-meson.build-check-for-all-linux-host_os-combinations.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/files/0001-meson.build-make-TLS-GLX-optional-again.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0001-mesa-demos-Add-missing-data-files.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0003-configure-Allow-to-disable-demos-which-require-GLEW-.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0004-Use-DEMOS_DATA_DIR-to-locate-data-files.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0007-Install-few-more-test-programs.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0008-glsl-perf-Add-few-missing-.glsl-.vert-.frag-files-to.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0009-glsl-perf-Install-.glsl-.vert-.frag-files.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0012-mesa-demos-OpenVG-demos-with-single-frame-need-eglSw.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos/0013-only-build-GLX-demos-if-needed.patch, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-demos_8.4.0.bb, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa-gl_19.0.5.bb, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa.inc, meta-luneos-backports-2.8/recipes-graphics/mesa/mesa_19.0.5.bb
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
=> Backport newer mesa from Yocto 2.8 Zeus

meta-luneos/recipes-webos/nyx-modules/nyx-modules.bb
=> nyx-modules: bump SRCREV

meta-luneos/recipes-webos/db8/db8.bb, meta-luneos/recipes-webos/db8/db8/0001-db8-Remove-references-to-com.webos.service.attacheds.patch, meta-luneui/recipes-webos/luna-service2-security-conf/luna-service2-security-conf.bb
=> db8, luna-service2-security-conf: Update to latest

meta-luneos/recipes-luneos/services/keymanager.bb
=> keymanager: bump SRCREV

meta-luneos/recipes-webos/app-services/app-services.bb, meta-luneos/recipes-webos/configurator/configurator.bb
=> app-services, configurator: Bump SRCREV

meta-luneos/recipes-core/packagegroups/packagegroup-webos-extended.bb, meta-luneos/recipes-devtools/fdisk/gptfdisk_%.bbappend, meta-luneos/recipes-upstreamable/gphotofs/gphotofs_0.5.bb, meta-luneos/recipes-webos/com.webos.service.pdm/com.webos.service.pdm.bb, meta-luneos/recipes-webos/pdm-plugin/pdm-plugin.bb
=> pdm & pdm-plugin: Add various bits to build & include in images.

meta-luneos/recipes-webos/app-services/app-services.bb
=> app-services: fix SRCREV

meta-luneos/recipes-luneos/services/imlibpurpleservice.bb, meta-luneos/recipes-webos/db8/db8.bb, meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-sysbus.bb
=> db8, imlibpurpleservice, nodejs-module-webos-sysbus: Bump SRCREV

meta-luneos/recipes-webos/core-apps/core-apps.bb, meta-luneos/recipes-webos/frameworks/enyo-1.0.bb
* fix visual issue with email app (MessagePanel)
* fix double clicking for expanders and combos
=> core-apps, enyo: bump SRCREV

meta-luneos/recipes-webos/luna-sysmgr/luna-sysmgr.bb, meta-luneos/recipes-webos/sleepd/sleepd.bb
Otherwise powerd might not be included in the final image.
=> luna-sysmgr: explicitely put RDEPENDS on powerd

meta-luneos/recipes-webos/nyx-modules/nyx-modules/a500.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/athene.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/grouper.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/hammerhead.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/maguro.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/mako.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/mido.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/onyx.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/pinephone.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/qemuarm.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/qemuarmv7a.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/qemux86-64.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/qemux86.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/rosy.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/tenderloin.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/tilapia.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/tissot.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/toro.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/toroplus.cmake
=> nyx-modules: Update copyright and provide modules to build for qemux86(-64)

meta-luneos/recipes-connectivity/ofono/ofono/0001-Enable-the-various-modem-plugins-we-support-again.patch, meta-luneos/recipes-connectivity/ofono/ofono/0002-Add-support-for-the-Ericsson-F5521gw-modem.patch, meta-luneos/recipes-connectivity/ofono/ofono/0003-configure.ac-always-require-libglibutil.patch, meta-luneos/recipes-connectivity/ofono/ofono_%.bbappend, meta-luneos/recipes-support/libglibutil/libglibutil.bb, meta-luneos/recipes-support/libglibutil/libglibutil/0001-Makefile-use-CC-from-bitbake.patch
=> [WIP] ofono: use more recent version

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-luneos/apps/messwerk.bb, meta-luneos/recipes-luneos/cardshell/luna-next-cardshell.bb, meta-luneos/recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0003-Qt-5.8-support.patch, meta-luneos/recipes-qt/qt5/qt5-qpa-hwcomposer-plugin_git.bb, meta-luneos/recipes-qt/qt5/qtsensors-sensorfw-plugin_git.bb, meta-luneos/recipes-support/sensorfw/sensorfw.bb, meta-luneos/recipes-support/sensorfw/sensorfw/0001-Fix-pkgconfig-version.patch, meta-luneos/recipes-support/sensorfw/sensorfw/0002-LuneOS-fix-systemd-service-file.patch, meta-luneos/recipes-support/sensorfw/sensorfw/0003-Fix-build-with-autohybris.patch, meta-luneos/recipes-support/sensorfw/sensorfw/0004-LuneOS-fix-dbus-service-file.patch, meta-luneos/recipes-support/sensorfw/sensorfw/90-dontbeevil.conf, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-iiosensors.conf
Don't merge this PR before https://github.com/webOS-ports/luna-next-cardshell/pull/318
=> Sensorfw rework to get iio sensors also working

meta-luneos/recipes-support/sensorfw/sensorfw.bb
Somehow the current SRCREV became incorrect (history rewriting?...)
=> sensorfw: fix SRCREV

meta-luneos/recipes-core/images/luneos-emulator-appliance/qemux86-64/luneos-emulator.ovf, meta-luneos/recipes-core/images/luneos-emulator-appliance/qemux86/luneos-emulator.ovf
=> luneos-emulator.ovf: Fix some grammar

meta-luneos/recipes-webos/pmklogd/pmklogd.bb, meta-luneos/recipes-webos/pmlogctl/pmlogctl.bb, meta-luneos/recipes-webos/pmlogdaemon/pmlogdaemon.bb
=> pm(logdaemon|klogd|logctl): Update to webOS OSE version

meta-luneos/recipes-core/busybox/busybox-static_1.30.1.bb, meta-luneos/recipes-core/images/luneos-package.inc
The goal is to include a static busybox in the sideloaded image.
=> busybox-static: introduce recipe

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/ucm/HiFi, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/ucm/sun50i-a64-audio.conf, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/webos-system.pa, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf_1.0.bb
=> pulseaudio-distro-conf: fix pinephone configuration

meta-luneos/recipes-support/sensorfw/sensorfw/sensord-pinephone.conf
=> sensorfw: fix orientation matrix for pinephone

meta-luneos/recipes-support/sensorfw/sensorfw/sensord-pinephone.conf
=> sensorfw: fix pinephone orientation matrix

meta-luneui/recipes-qt/qt5/qtwebengine/0012-screenInfoFromQScreen-fallback-on-primary-screen-if-.patch, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
=> qtwebengine: fix default screen information retrieval

meta-luneos/recipes-luneos/cardshell/luna-next-cardshell.bb
=> luna-next-cardshell: bump SRCREV

meta-luneos/recipes-luneos/audio-service/audio-service.bb
=> audio-service: bump SRCREV

meta-luneos/recipes-luneos/cardshell/luna-next-cardshell.bb, meta-luneos/recipes-luneos/webos-telephonyd/webos-telephonyd.bb
* simplifies com.palm.telephony subscription
* merge herrie/acg branch in main branch for webos-telephonyd
=> luna-next-cardshell, webos-telephonyd: bump SRCREV

meta-luneos/recipes-connectivity/ofono/ofono-conf.bb, meta-luneos/recipes-connectivity/ofono/ofono-conf/mido/ril_subscription.conf, meta-luneos/recipes-connectivity/ofono/ofono-conf/rosy/ril_subscription.conf, meta-luneos/recipes-connectivity/ofono/ofono-conf/tissot/ril_subscription.conf, meta-luneos/recipes-connectivity/ofono/ofono_%.bbappend, meta-luneos/recipes-support/libgrilio/libgrilio.bb
Various bits to get at least both sims working in oFono.
=> Initial small work for multi-sim support

meta-luneos/recipes-webos/nyx-modules/nyx-modules.bb, meta-luneos/recipes-webos/nyx-modules/nyx-modules/pinephone.cmake
=> nyx-modules: fix touchpanel and pinephone touchpanel device path

meta-luneos/recipes-support/sensorfw/sensorfw.bb
=> sensorfw: Use binder for tenderloin

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/ucm2/HiFi, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/ucm2/PinePhone.conf, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/ucm2/VoiceCall, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/webos-system.pa, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf_1.0.bb
PR also depends on https://github.com/webOS-ports/meta-pine64-luneos/pull/14
=> pulseaudio-distro-conf: fix Pinephone UCM config

meta-luneos/recipes-luneos/apps/messwerk.bb, meta-luneos/recipes-support/bluebinder/bluebinder.bb, meta-luneos/recipes-support/bluebinder/bluebinder/0002-service-load-after-wifi-module-load.patch
=> bluebinder: load after wlan module on tissot

meta-luneos/recipes-luneos/luneos-default-wallpapers/luneos-default-wallpapers.bb
=> luneos-default-wallpapers: install images in datadir

meta-luneos/recipes-luneos/services/org.webosports.service.messaging.bb
Pointing to the wrong location to start with didn't help, let's force installing them similar like we do in other recipes.
=> org.webosports.service.messaging: Fix installation of LS2 ACG files

meta-luneos/recipes-multimedia/pulseaudio/audiosystem-passthrough.bb, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/webos-system.pa, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid-hidl_git.bb, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid_git.bb
Ads support for headphones in Android 9.
Seems the Mobian version added support for headphone detection using libevdev for Android 9.
=> Audio: Various bits for getting more Android 9 devices to work properly.

meta-luneos/recipes-webos/luna-appmanager/luna-appmanager.bb
=> luna-appmanager: fix spurious spaces

meta-luneos/recipes-webos/appinstalld2/appinstalld2.bb, meta-luneos/recipes-webos/applicationinstallerutility/applicationinstallerutility.bb, meta-luneos/recipes-webos/luna-downloadmgr/luna-downloadmgr.bb
=> appinstalld migration: fix some fetch issues

meta-luneos/recipes-luneos/apps/org.webosports.app.firstuse.bb, meta-luneos/recipes-luneos/apps/org.webosports.app.preware.bb, meta-luneos/recipes-luneos/luneos-components/luneos-components.bb, meta-luneos/recipes-luneos/services/org.webosports.service.ipkg.bb
=> preware: bump SRCREV

meta-luneos/recipes-webos/appinstalld2/appinstalld2.bb
=> appinstalld2: bump SRCREV

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86-64/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/surface-manager.service, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0001-Fix-build-for-Qt-5.15.2.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0002-Add-capability-to-pass-extra-options-to-surface-mana.patch
=> luna-surfacemanager: provide a way to override LSM env variables

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86-64/99-virtualbox-mouse.rules, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86-64/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86/99-virtualbox-mouse.rules, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86/surface-manager.env
=> luna-surfacemanager-conf: fix QT_QPA_EVDEV_MOUSE_PARAMETERS

meta-luneos/recipes-webos/chromium/files/0035-Add-window.open-support.patch, meta-luneos/recipes-webos/chromium/webruntime-repo_91.inc, meta-luneos/recipes-webos/wam/wam.bb, meta-luneos/recipes-webos/wam/wam/0005-Add-relaunch-support-for-legacy-enyo-apps.patch, meta-luneos/recipes-webos/wam/wam/0006-Add-window.open-support.patch
=> wam, webruntime: initial support for window.open

meta-luneos/conf/layer.conf, meta-luneos/recipes-webos/configd-data/configd-data.bb
=> configd-data: Add MACHINE specific configuration files.

meta-luneos/recipes-webos/chromium/files/0037-WebOSServiceBridgeInjection-fix-JSON-input-test.patch, meta-luneos/recipes-webos/chromium/webruntime-repo_91.inc
=> chromium: fix crash in PalmServiceBridge

meta-luneos/recipes-luneos/apps/org.webosports.app.firstuse.bb
=> org.webosports.app.firstuse: bump SRCREV

meta-luneos/recipes-webos/luna-appmanager/luna-appmanager.bb
=> luna-appmanager: bump SRCREV

meta-luneos/conf/distro/include/luneos-preferred-providers.inc, meta-luneos/recipes-luneos/luna-next-cardshell/luna-next-cardshell.bb, meta-luneos/recipes-luneos/webos-keyboard/webos-keyboard.bb, meta-luneos/recipes-webos/maliit-framework-webos/files/0001-Correctly-detect-wayland-platform.patch, meta-luneos/recipes-webos/maliit-framework-webos/files/maliit-env.conf, meta-luneos/recipes-webos/maliit-framework-webos/files/maliit-server.conf, meta-luneos/recipes-webos/maliit-framework-webos/files/maliit-server.service, meta-luneos/recipes-webos/maliit-framework-webos/files/maliit-server.sh.in, meta-luneos/recipes-webos/maliit-framework-webos/files/maliit-server@.service, meta-luneos/recipes-webos/maliit-framework-webos/maliit-framework-webos.bb
=> luna-next-cardshell, Maliit: various fixes

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/mido/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/grouper/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/hammerhead/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/maguro/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/mako/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/onyx/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/oxygen/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/pinephone/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/pinephonepro/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/raspberrypi2/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/raspberrypi3/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/raspberrypi4/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/rosy/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/s2/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/sagit/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/sargo/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/tenderloin/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/tissot/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/todo/yggdrasil/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0002-Add-capability-to-pass-extra-options-to-surface-mana.patch
Based on values in luna-next-conf
=> luna-surfacemanager-conf: Add surface-manager.env for all our targets

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/surface-manager.service, meta-luneos/recipes-webos/sam/sam.bb
*Fixes Maliit keyboard not showing up in native/QML apps
=> sam: bump SRCREV

meta-luneos/recipes-luneos/luna-next-cardshell/luna-next-cardshell.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/hammerhead/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/mako/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/mido/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/onyx/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/oxygen/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/pinephone/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/pinephonepro/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86-64/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/qemux86/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/raspberrypi2/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/raspberrypi3/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/raspberrypi4/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/rosy/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/s2/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/sagit/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/sargo/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/tenderloin/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/tissot/surface-manager.env, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/yggdrasil/surface-manager.env
=> surface-manager, cardshell: fix theming

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinephone/webos-system.pa
=> pulseaudio-distro-conf: pinephone: setup default output port

meta-luneos/recipes-webos/qml-webos-framework/qml-webos-framework.bb, meta-luneos/recipes-webos/qml-webos-framework/qml-webos-framework/0006-AppLoader-use-old-syntax-for-quit-connect.patch
=> qml-webos-framework: fix QML quit signal

meta-luneos/recipes-webos/chromium/files/0042-palmGetResource-improve-legacy-compatibility.patch, meta-luneos/recipes-webos/chromium/webruntime-repo_91.inc
=> webruntime: add palmGetResource patch

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0001-Add-capability-to-pass-extra-options-to-surface-mana.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0002-WebOSShellSurface-add-setClientSize.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0003-webosscreenshot-respect-QT_OPENGL_ES.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0004-DefaultSettings.qml-Use-Prelude-for-LuneOS.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0005-Update-com.webos.surfacemanager.role.json.in.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0006-product.env.in-Make-it-work-with-non-drm-devices.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0007-Add-additional-permissions-for-org.webosports.notifi.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0008-base.pro-Remove-building-of-tests.patch, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0009-com.webos.surfacemanager.perm.json-Add-permissions-f.patch, meta-luneos/recipes-webos/luna-sysservice/luna-sysservice/0001-luna-sysservice-Add-service-file-for-systemd.patch, meta-luneos/recipes-webos/luna-sysservice/luna-sysservice/0002-Add-ImageService.patch, meta-luneos/recipes-webos/luna-sysservice/luna-sysservice/0003-luna-sysservice-Fix-spacing-issues.patch, meta-luneos/recipes-webos/luna-sysservice/luna-sysservice/0004-luna-sysservice-Add-required-bits-for-LuneOS.patch, meta-luneos/recipes-webos/sam/sam/0001-sam-Add-systemd-service-file.patch, meta-luneos/recipes-webos/sam/sam/0002-Add-sam.sh-script-from-webos-initscripts-and-install.patch, meta-luneos/recipes-webos/sam/sam/0003-com.webos.sam.role.json.in-Fix-various-outbound-perm.patch, meta-luneos/recipes-webos/sam/sam/0004-Allow-getAppBasePath-also-from-trusted-apps.patch, meta-luneos/recipes-webos/sam/sam/0005-RunningApp-disable-killer-timeout-for-app-relaunch.patch, meta-luneos/recipes-webos/sam/sam/0006-Setup-QML-style-for-LuneOS.patch, meta-luneos/recipes-webos/sam/sam/0007-Handle-noWindow-apps.patch, meta-luneos/recipes-webos/sam/sam/0008-AppDescription.h-Add-org.webosports-as-privileged-as.patch, meta-luneos/recipes-webos/sam/sam/0009-LuneOS-style-module-name-is-now-QtQuick.Controls.Lun.patch, meta-luneos/recipes-webos/sam/sam/0010-Setup-QT_IM_MODULE-for-client-apps.patch
=> luna-surfacemanager,luna-sysservice,sam: fix patches

meta-luneos/recipes-luneos/luna-next-cardshell/luna-next-cardshell.bb, meta-luneos/recipes-webos/app-services/app-services.bb, meta-luneos/recipes-webos/core-apps/core-apps.bb
To fix various permission issues and let FirstUse finish gracefully.
=> [WIP] luna-next-cardshell, app-services, core-apps: Bump SRCREV

meta-luneos/recipes-luneos/apps/org.webosports.app.messaging.bb, meta-luneos/recipes-luneos/luna-next-cardshell/luna-next-cardshell.bb, meta-luneos/recipes-luneos/services/org.webosports.service.messaging.bb, meta-luneos/recipes-luneos/webos-telephonyd/webos-telephonyd.bb, meta-luneos/recipes-webos/app-services/app-services.bb, meta-luneos/recipes-webos/core-apps/core-apps.bb, meta-luneos/recipes-webos/mojomail/mojomail.inc
Should get account app and email in a reasonable state
=> More fixes

meta-luneos/recipes-luneos/apps/org.webosports.app.phone.bb
=> org.webosports.app.phone.bb: bump SRCREV

meta-luneos/recipes-connectivity/connman/connman-conf/main.conf
=> connman: blacklist usb interface

meta-luneos/recipes-qt/qt6/qt6-qpa-hwcomposer-plugin_git.bb
=> qt6-qpa-hwcomposer-plugin: bump SRCREV

meta-luneos/recipes-luneos/apps/org.webosports.app.contacts.bb, meta-luneos/recipes-webos/sam/sam.bb, meta-luneos/recipes-webos/sam/sam/0011-NativeContainer-configure-native-apps.patch, meta-luneos/recipes-webos/wam/wam.bb
=> sam: setup environment for native apps

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-luneos/apps/org.webosports.app.terminal.bb, meta-luneos/recipes-qt/qmltermwidget/qmltermwidget.bb
There is still a focus issue, but the app starts.
=> qmltermwidget,org.webosports.app.terminal: migrate to Qt6

meta-luneos/recipes-connectivity/ofono/ofono-conf/pinetab2/environment.conf, meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinetab2/ucm2/HiFi.conf, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinetab2/ucm2/PineTab2.conf, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinetab2/ucm2/VoiceCall.conf, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/pinetab2/webos-system.pa, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf_1.0.bb, meta-luneos/recipes-qt/qt6/qtbase_git.bbappend, meta-luneos/recipes-support/sensorfw/sensorfw.bb, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-pinetab2.conf, meta-luneos/recipes-support/waydroid/waydroid.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager-conf/pinetab2/surface-manager.env, meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf/pinetab2/luna-platform.conf, meta-luneos/recipes-webos/nyx-conf/nyx-conf/pinetab2/nyx.conf, meta-luneos/recipes-webos/nyx-modules/nyx-modules/pinetab2.cmake
Initial work on PineTab2 support
=> meta-webos-ports: Add Pine64 PineTab2

meta-luneos/conf/distro/include/luneos.inc
=> Update luneos.inc: Add Ubuntu 23.04 to sanity tested distros

meta-luneos/recipes-webos/webos-connman-adapter/webos-connman-adapter/0003-Update-webos-connman-adapter.role.json.in-Add-permis.patch
To fix permission errors with com.webos.lunasend-*
=> webos-connman-adapter: Update patch

meta-luneos/recipes-webos/sleepd/sleepd.bb, meta-luneos/recipes-webos/sleepd/sleepd/0012-com.webos.service.sleep.api.json.in-Add-API-for-susp.patch
=> sleepd: Fix missing API issue

meta-luneos/recipes-webos/bootd/bootd.bb, meta-luneos/recipes-webos/configurator/configurator.bb, meta-luneos/recipes-webos/event-monitor/event-monitor.bb, meta-luneos/recipes-webos/filecache/filecache.bb, meta-luneos/recipes-webos/luna-downloadmgr/luna-downloadmgr.bb, meta-luneos/recipes-webos/luna-sysmgr-conf/luna-sysmgr-conf.bb, meta-luneos/recipes-webos/luna-sysservice/luna-sysservice.bb, meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-sysbus.bb, meta-luneos/recipes-webos/qml-app-components/qml-app-components.bb, meta-luneos/recipes-webos/qml-webos-framework/qml-webos-framework.bb, meta-luneos/recipes-webos/qt-features-webos/qt-features-webos.bb, meta-luneos/recipes-webos/sam/sam.bb, meta-luneos/recipes-webos/settingsservice/settingsservice.bb, meta-luneos/recipes-webos/webos-connman-adapter/wca-support-api.bb, meta-luneos/recipes-webos/webos-connman-adapter/wca-support.bb, meta-luneos/recipes-webos/webos-fontconfig-files/webos-fontconfig-files.bb, meta-luneos/recipes-webos/webos-wayland-extensions/webos-wayland-extensions.bb, meta-luneui/recipes-webos/luna-service2/luna-service2.bb, meta-luneui/recipes-webos/luna-sysmgr-ipc/luna-sysmgr-ipc.bb, meta-luneui/recipes-webos/nyx-lib/nyx-lib.bb, meta-luneui/recipes-webos/serviceinstaller/serviceinstaller.bb, meta-luneui/recipes-webos/vmwgfx-layout/vmwgfx-layout.bb
Since it was all over the place, use 4 spaces before the file:// patches.
=> meta-webos-ports: Unify patches indentation

meta-luneos/recipes-support/sensorfw/sensorfw.bb, meta-luneos/recipes-support/sensorfw/sensorfw/0001-hybrisadaptor-Fix-deprecated-use-of-QMap-insertMulti.patch, meta-luneos/recipes-webos/configd-data/configd-data.bb
=> Minor fixes

meta-luneos/recipes-webos/notificationmgr/notificationmgr/0003-com.webos.notification.role.json.in-Fix-permission-i.patch
This is usefull when dealing with toasts
=> notificationmgr: allow com.webos.surfacemanager*

meta-luneos/recipes-webos/nyx-modules/nyx-modules/0002-nyx-modules-Add-haptics-module.patch
This is currently only a very basic implementation.
=> nyx-modules: provide support for gpio vibrator

meta-luneos/recipes-support/waydroid/waydroid.bb
So we can launch it from launcher simply
=> waydroid.bb: Cleanup recipe & automate integration

meta-luneui/recipes-webos/luna-service2/luna-service2.bb, meta-luneui/recipes-webos/luna-service2/luna-service2/0006-LSMessageIsSubscription-test-if-payload-is-a-JSON-ob.patch
This error isn't fatal, but it looks bad in the logs.
=> luna-service2: add jis_object test to avoid error in log

meta-luneos/conf/distro/include/luneos.inc, meta-luneos/recipes-core/packagegroups/packagegroup-webos-extended.bb, meta-luneos/recipes-qt/qt6/qtwayland_git.bbappend
Initial work to get RPi3/RPi4 building again.
UI works, WAM works, WiFi & BT work, so good enough to start with.
=> Additions to get RPi3/RPi4 to build again

meta-luneos/recipes-connectivity/ofono/ofono-conf/raspberrypi3/environment.conf
- Quiet ofonod spitting out messages about not finding the RIL every 5 seconds
=> ofono: Remove RIL ofono plugin for raspberrypi3

meta-luneos/recipes-webos-owo/luna-sysmgr/luna-sysmgr.bb
- Add LUNEOS_BOOT_APPS and override the existing .conf line
=> luna-sysmgr: Make LaunchAtBoot applications list configurable at the bitbake level

meta-luneos/recipes-luneos/nyx-conf/nyx-conf/sargo/nyx.conf, meta-luneos/recipes-webos-ose/nyx-modules/nyx-modules/sargo.cmake, meta-luneos/recipes-webos-owo/luna-sysmgr-conf/luna-sysmgr-conf/sargo/luna-platform.conf
To bring it into a bit better state.
UI boots, rotation works. Audio, WLAN and Telephony KO still.
=> Various fixes for Sargo

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-distro-conf/sargo/webos-system.pa
=> pulseaudio-distro-conf: Add webos-system.pa for sargo

meta-luneos/conf/distro/include/defaulttunes.inc
So webruntime is happy to build :)
=> defaulttunes.inc: Add PACKAGE_EXTRA_ARCHS for mako

meta-luneos/recipes-webos-ose/activitymanager/activitymanager.bb, meta-luneos/recipes-webos-ose/activitymanager/activitymanager/0003-activitymanager-Fix-outbound-permissions-to-com.webo.patch, meta-luneos/recipes-webos-ose/bluetooth/com.webos.service.bluetooth2/0001-com.webos.service.bluetooth2.role.json.in-Add-additi.patch, meta-luneos/recipes-webos-ose/com.webos.service.memorymanager/com.webos.service.memorymanager.bb, meta-luneos/recipes-webos-ose/com.webos.service.memorymanager/com.webos.service.memorymanager/0001-com.webos.service.memorymanager-Fix-outbound-permiss.patch
=> Fix permission errors

meta-luneos/recipes-core/systemd/systemd/0001-systemd-oomd-depend-on-swap-on.patch, meta-luneos/recipes-core/systemd/systemd/0002-Add-webos-interface.patch, meta-luneos/recipes-core/systemd/systemd/0003-systemd-oomd-modify-oomd.conf.patch, meta-luneos/recipes-core/systemd/systemd/0004-oomd-to-some.patch, meta-luneos/recipes-core/systemd/systemd/0005-oomd-change-duration.patch, meta-luneos/recipes-core/systemd/systemd/0006-Change-ownership-of-media-directory-to-support-non-r.patch, meta-luneos/recipes-core/systemd/systemd_%.bbappend
* Add webOS memorymanager interface
* Change ownership of /media to media:media to keep media services happy.
=> systemd: Add OSE's patches for systemd
