meta-luneos/recipes-support/nemo-qml-plugin-dbus/nemo-qml-plugin-dbus_git.bb
Needed e.g. for calling bluez dbus service from system menu(qml).
Signed-off-by: Nikolay Nizov <nizovn@gmail.com>
=> nemo-qml-plugin-dbus: add recipe

meta-luneos/recipes-webos/luna-appmanager/luna-appmanager.bb
=> luna-appmanager: replace qtquick1 dependency with qtdeclarative

meta-luneos/recipes-connectivity/ofono/ofono_git.bbappend
Upgrading to 1.19 breaks ofono on hammerhead (at least)
=> ofono: revert back to 1.17

meta-luneos/recipes-core/libhybris/libhybris_git.bbappend
This reverts commit 076b2c0cca5f7e812b62e8f757e1281e7eb4f4b5.
The merge of Ubuntu's changes for Android 6 and aarch64 are leading
to issues when used with our CM12.1 HAL. So let's delay this bump
until we solve those problems.
=> Revert "libhybris: bump SRCREV"

meta-luneui/recipes-graphics/mesa/mesa_%.bbappend
Starting Qt-X11 sessions will complain with
| Failed to create display (No such file or directory)
Tested with Qt5.8 on RaspiPi/Mesa/VC4 with lxqt-x11 and liri-wayland
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
=> mesa: do not move around libGLESv2.so

meta-luneui/recipes-qt/qt5/qtwebengine/chromium/0001-Add-PalmServiceBridge-to-WebEngine.patch, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
we had "patchdir=./src/3rdparty", while meta-qt5 had
"patchdir=src/3rdparty"; both point to the same directory, but bitbake
thinks its two separate things, so it teats them separately. When
creating the "patches/series" file for our patches, it then overwrites
by mistake the one that was created for meta-qt5 in the same directory.
=> qtwebengine: fix chromium patches's patchdir

meta-luneos/recipes-webos/nyx-conf/nyx-conf/tenderloin/nyx.conf
This re-enables the Power key to work correctly.
=> nyx-conf: add event0 to the keys managed by nyx.

meta-luneos/recipes-qt/qt5/qtscenegraph-adaptation_git.bb
The problematic commit has been forced out of 'master' branch,
as it didn't built with Qt 5.6. A fix has been provided in the
'Tofe' fork, but isn't merged yet.
In the meantime, use that 'Tofe' repository.
=> qtscenegraph-adaptation: fix URI

meta-luneui/recipes-qt/qt5/qtwayland/0003-QtKeyExtensionGlobal-fix-export.patch, meta-luneui/recipes-qt/qt5/qtwayland_git.bbappend
This extension, though experimental, lets luna-next send
easily Qt key strokes, without needing to set a native key code.
=> qtwayland: Fix QtKeyExtensionGlobal's export

meta-luneos/recipes-multimedia/qtubuntu-camera/qtubuntu-camera_bzr.bb, meta-luneos/recipes-qt/qt5/qtsensors-sensorfw-plugin_git.bb, meta-luneos/recipes-qt/qt5/qtsensors_git.bbappend
The bitbake error would happen when qtubuntu-camera recipe
is rebuilt without re-fetching the source
=> Fixes for qtubuntu-camera and qtsensors

meta-luneos/recipes-connectivity/ofono/ofono-conf/qemux86-64/environment.conf, meta-luneos/recipes-connectivity/ofono/ofono-conf/qemux86/environment.conf
Disable RIL modem driver for qemux86 and qemux86-64 to avoid log spamming.
=> ofono-conf: Make sure we don't use RIL on qemu

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb
Needed to QtBluetooth which we want to use in Luna-Next-Cardshell and QML version of Settings App.
=> packagegroup-luneos-extended: Add qtconnectivity

meta-luneos/recipes-luneos/apps/org.webosports.app.settings-qml.bb
Depends on https://github.com/webOS-ports/luna-qml-launcher/pull/12
This recipe isn't requested by any target, on purpose, as the app is far from being usable yet.
=> org.webosports.app.settings: add QML variant

meta-luneos/recipes-connectivity/connman/libconnman-qt5/0001-Fix-initial-value-of-connected-property.patch, meta-luneos/recipes-connectivity/connman/libconnman-qt5_git.bbappend
Note: This patch has also been to upstream.
=> libconnman-qt5: fix initial value of "connected" property

meta-luneos/recipes-webos/nyx-conf/nyx-conf/hammerhead/nyx.conf
=> nyx-conf: do not let keys module watch over the touchpanel

meta-luneos/recipes-core/libhybris/libhybris_git.bbappend
To make sure build works correctly.
=> libhybris: Set --enable-arch=arm64 for aarch64

meta-luneos/recipes-core/initrdscripts/initramfs-boot-android/distro.conf, meta-luneos/recipes-core/initrdscripts/initramfs-boot-android/init.sh
- Use FunctionFS for ADB instead of custom ADB gadget
- Mount system partition in order to be able to access build.prop for ADB
- Extract the SD card device name from the partition name. This allows booting on devices, like the i9300, where the SD card is not mmcblk0.
=> initramfs-boot-android: Various fixes to init.sh

meta-luneos/recipes-core/libhybris/libhybris_git.bbappend
--with-default-hybris-ld-library-path is not needed anymore with Halium based builds, so dropping it. 
Bumping SRCREV so libhyrbis doesn't look in /system/lib anymore for libhardware.so, so it will work on aarch64 as well.
=> libhyrbis: Drop --with-default-hybris-ld-library-path and bump SRCREV

meta-luneui/recipes-qt/qt5/qtbase/0002-Add-additional-Adreno-targets-for-needsWorkaround.patch, meta-luneui/recipes-qt/qt5/qtbase_git.bbappend
mido uses Snapdragon 625 with Adreno 506 GPU which isn't patched yet into QT as needing "needsWorkaround". This has been submitted upstream with https://bugreports.qt.io/browse/QTBUG-66702 and https://codereview.qt-project.org/#/c/221471/
Once merged upstream this can be dropped.
=> qtbase: Add patch to fix quirks with newer Adreno GPU's

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneui/recipes-qt/qt5/qtwebengine_git.bbappend
Having libpci lets Chromium better determine which
optimizations/workarounds to apply for the GPU. This fixes
a crash with Qt 5.9.4.
=> packagegroup-luneos-extended: include libpci for qemux86

meta-luneos/recipes-webos/nyx-modules/nyx-modules/athene.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/mido.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/onyx.cmake, meta-luneos/recipes-webos/nyx-modules/nyx-modules/rosy.cmake
Wrong device names were used in the cmake files.
=> nyx-modules: Fix devices names in cmake files

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb
Depends on https://github.com/webOS-ports/nyx-modules-hybris/pull/4
=> packagegroup-luneos-extended: re-enable nyx-modules-hybris

meta-luneui/recipes-webos/luna-service2/luna-service2.bb
Depends on https://github.com/webOS-ports/luna-service2/pull/6
=> luna-service2: bump SRCREV

meta-luneos/recipes-core/initrdscripts/initramfs-boot-android/init.sh
These checks break android's ramdisk extraction with busybox's cpio.
=> initramfs-boot-android: disable busybox extreme symlink checks

meta-luneos/recipes-core/systemd/systemd/Reroute-chase_symlinks-to-canonicalize_file_name-for.patch, meta-luneos/recipes-core/systemd/systemd_%.bbappend
For LuneOS, it means all ARM 32bit targets.
=> systemd: fix boot for old kernels

meta-luneui/recipes-qt/qt5/qtwayland/0004-compositor-fix-private-objects-inheritance.patch, meta-luneui/recipes-qt/qt5/qtwayland_git.bbappend
This could cause crashes when using QWaylandWlShell API.
=> qtwayland: fix QWaylandShellPrivate inheritance

meta-luneos/recipes-core/initrdscripts/initramfs-boot-android/init.sh
keeping a value for the hotplug uevent seems to conflict with
Android's ueventd daemon, and causes kernel crashes.
So cleanup this value when mdev isn't needed anymore, which is
what should be done anyway.
=> initramfs-boot-android: reset uevent_help when stopping mdev

meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-dynaload.bb, meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-sysbus.bb
* fix build with nodejs 10.0
Depends on https://github.com/webOS-ports/nodejs-module-webos-dynaload/pull/2 and https://github.com/webOS-ports/nodejs-module-webos-sysbus/pull/2
=> nodejs-module-webos-{dynaload,sysbus}: bump SRCREV

meta-luneos/recipes-core/initrdscripts/initramfs-boot-android/init.sh
Putting this flag directly in ${rootmnt} doesn't make sense if we intend
to have our rootfs read-only... so put the flag in the data folder.
=>  initramfs-boot-android: put .firstboot_done in a rw folder

meta-luneos/recipes-graphics/sdl2-opengles-test/sdl2-opengles-test_git.bb
Together with
https://github.com/agherzan/meta-raspberrypi/pull/412
https://github.com/webOS-ports/meta-rpi-luneos/pull/7
fixes all current signatures issues detected with:
openembedded-core/scripts/sstate-diff-machines.sh --targets=luneos-dev-image --tmpdir=tmp-glibc/ --analyze --machines="raspberrypi2 raspberrypi3 mako"
=> sdl2-opengles-test: build only sdl2_opengles2_test for all rpi MACHINEs

meta-luneos/recipes-luneos/cardshell/luna-next-cardshell.bb, meta-luneui/recipes-luneui/luna-next/luna-next.bb
NB: Depends on https://github.com/webOS-ports/luna-next/pull/141 and https://github.com/webOS-ports/luna-next-cardshell/pull/315!
* Fix window activation handling, preventing vkb to show up
* Fix JustTypeLauncher focus
=> luna-next and cardshell: bump SRCREV

meta-luneos/recipes-qt/maliit/maliit-framework-qt5/maliit-env.conf
Fixes the display of maliit on qemux86 target
=> maliit-framework-qt5: set QT_QPA_PLATFORM=wayland

meta-luneos/recipes-support/ntp/ntp_%.bbappend
Fixes: May 08 23:59:11 hammerhead sntp[2291]: kod_init_kod_db(): Cannot open KoD db file /var/db/ntp-kod: No such file or directory
=> ntp: Add an empty ntp-kod file

meta-luneos/recipes-luneos/services/imaccountvalidator.bb, meta-luneos/recipes-luneos/services/imlibpurpleservice.bb, meta-luneos/recipes-support/pidgin/icyque_git.bb
Old ICQ/AOL plugin is no longer working, therefore remove them. 
Add new icyque plugin that supports the new WIM protocol.
=> Remove old and add new ICQ/AOL plugin

meta-luneos/recipes-webos/bootd/bootd.bb
We need to add the systemd service file to the forked repo and inherit webos_systemd so it gets installed into the right location.
=> bootd: Fix systemd service file

meta-luneos/recipes-luneos/services/org.webosports.cdav.bb, meta-luneos/recipes-luneos/services/org.webosports.service.update.bb, meta-luneos/recipes-webos/frameworks/mojoservice-frameworks.bb, meta-luneos/recipes-webos/mojomail/mojomail.inc
Which include the changes for internetConfidence = fair to internet = true to allow working with new ActivityManager in OSE.
=> mojo: Switch to webOS-ports/webOS-OSE branches

meta-luneos/recipes-core/images/luneos-emulator-appliance.inc, meta-luneos/recipes-core/images/luneos-package.inc
* ${IMAGE_VERSION_SUFFIX} starts with dash
* include MACHINE in the appliance name, to clearly show if it's qemux86 or qemux86-64
WIP: still testing it locally
=> luneos-{package,emulator-appliance}.inc: remove extra dash in filenames

meta-luneos/recipes-core/systemd/systemd-serialgetty.bbappend
=> systemd-serialgetty: disable SERIAL_CONSOLES on LuneOS's qemu

meta-luneos/recipes-core/systemd/systemd_%.bbappend
luna-sysservice needs timedatectl to work properly.
=> systemd: reenable timesyncd

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-support/sensorfw/sensorfw.bb, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-iiosensors.conf, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-pinephone.conf
To have sensorfw recipe use a machine-dedicated configuration file, it
is now only needed to provide the sensord-${MACHINE}.conf file.
=> sensorfw: reorganize recipe to have more common code

meta-luneui/recipes-qt/qt5/qtwayland/0005-Fix-compilation-of-linuxdmabuf.patch, meta-luneui/recipes-qt/qt5/qtwayland_git.bbappend
For Pinephone we need a newer version of Mesa, and that breaks one of
the plugins of qtwayland.
Indeed, eglmesaext.h doesn't get indirectly included by eglext.h, and
some typedefs aren't defined anymore.
This patch will become useless when Mesa ships with an updated set of
Khronos headers, because https://github.com/KhronosGroup/EGL-Registry/pull/95
has now been merged.
=> qtwayland: fix compilation with Pinephone's version of Mesa

meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-dynaload.bb, meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-pmlog.bb, meta-luneos/recipes-webos/nodejs-module-webos/nodejs-module-webos-sysbus.bb
This version also builds with node.js 10 from zeus branch.
=> nodejs-module-webos-*: fix build with node.js 12

meta-luneos/recipes-graphics/wayland/wayland_%.bbappend, meta-luneui/recipes-qt/qt5/qtbase/0002-QThreadData-use-libpthread-instead-of-gcc-TLS.patch, meta-luneui/recipes-qt/qt5/qtbase_git.bbappend
Instead of wayland-egl provided by libhybris, should be merged together with https://github.com/shr-distribution/meta-smartphone/pull/116
=> Use upstream wayland-egl for our devices

meta-luneos/recipes-webos/nyx-modules/nyx-modules.bb, meta-luneos/recipes-webos/nyx-modules/nyx-modules/tenderloin.cmake
* WEBOS_INSTALL_ROOT is '/':
meta-luneui/classes/webos_cmake.bbclass:EXTRA_OECMAKE += "-DWEBOS_INSTALL_ROOT:PATH=/"
and ${WEBOS_INSTALL_ROOT}/lib/systemd/system
then starts with // which CMake doesn't like:
| CMake Error at cmake_install.cmake:54 (file):
|   file called with network path DESTINATION.  This does not make sense when
|   using DESTDIR.  Specify local absolute path or remove DESTDIR environment
|   variable.
|
|   DESTINATION=
|
|   //lib/systemd/system/nyx.target.d
* now both nyx-modules and nyx-modules-hybris would try to install this
files/systemd/nyx.target.d/wait-touchscreen.conf
but it only exists in nyx-modules repo since:
commit 2332bec773c4660d9fc6df56efd0bbf38f84604d
Author: Nikolay Nizov <nizovn@gmail.com>
Date:   Sat Sep 10 15:27:45 2016 +0300
tenderloin: wait for …
=> nyx-modules-hybris: fix install path for tenderloin

meta-luneos/recipes-webos/nyx-modules/nyx-modules.bb, meta-luneos/recipes-webos/nyx-modules/nyx-modules/tenderloin.cmake
* move the /lib/systemd/system/nyx.target.d/wait-touchscreen.conf installation
from tenderloin.cmake to do_install_append_tenderloin, because tenderloin.cmake
is reused also by nyx-modules-hybris
* also make it to respect systemd_system_unitdir variable
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
=> nyx-modules: fix wait-touchscreen.conf installation for tenderloin

meta-luneos/recipes-webos/nyx-modules/nyx-modules/tenderloin.cmake
=> nyx-modules: tenderloin: use haptics modules from OSE

meta-luneos/recipes-support/sensorfw/sensorfw.bb, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-tenderloin.conf
Accelerometer can be used directly from /dev, without using Halium's
driver.
=> sensorfw: tenderloin: don't use Halium

meta-luneui/recipes-luneui/luna-next/luna-next-conf/tenderloin/environment.conf
This can cause gstreamer to crash, if the cached data can't be read
correctly.
=> luna-next-conf: For tenderloin, $HOME/.cache can conflict with webOS one

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb
Dropped the ${QEMU_RDEPENDS} by mistake when trying to disable the build of waydroid by default.
=> packagegroup-luneos-extended: Fix RDEPENDS for qemux86-64

meta-luneos/recipes-webos/chromium/files/0034-run_app_shell-fix-XDG_RUNTIME_DIR-for-LuneOS.patch, meta-luneos/recipes-webos/chromium/webruntime-repo_91.inc
Fix XDG_RUNTIME_DIR value, leading to app_shell crashing on startup
=> webruntime: fix app_shell wrapper

meta-luneos/conf/layer.conf, meta-luneos/recipes-support/rng-tools/rng-tools/tenderloin/rngd.service, meta-luneos/recipes-support/rng-tools/rng-tools_%.bbappend
By reverting: https://github.com/openembedded/openembedded-core/commit/e9715d4234eb7b45dee8b323799014646f0a1b07
Reduces boot time by about 2 minutes from 210 seconds to 90 seconds.
=> rng-tools: Speed up boot time

meta-luneos/recipes-webos/frameworks/enyo-1.0.bb
Fixes the following in the webinspector in Enyo 1.0 apps:
Access is blocked to resource: file:///usr/palm/frameworks/tellurium/tellurium_config.json
enyo-build.js:1756 GET chrome-error://chromeillegalwebdata/ net::ERR_ACCESS_DENIED
=> enyo-1.0: Add symlink for tellurium

meta-luneos/recipes-core/packagegroups/packagegroup-webos-extended.bb, meta-luneos/recipes-graphics/fontconfig/fontconfig_%.bbappend, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0005-DefaultSettings.qml-Use-Prelude-for-LuneOS.patch, meta-luneos/recipes-webos/qml-app-components/qml-app-components.bb, meta-luneos/recipes-webos/qml-app-components/qml-app-components/0001-FontStyle.qml-Use-Prelude-on-LuneOS-instead-of-Museo.patch, meta-luneos/recipes-webos/webos-fontconfig-files/webos-fontconfig-files.bb, meta-luneos/recipes-webos/webos-fontconfig-files/webos-fontconfig-files/0001-31-webos-aliases.conf-Use-Prelude-for-LuneOS.patch
Use fontconfig for setting Prelude system wide for LuneOS and patch places where it uses other fonts from OSE.
=> Use Prelude system wide for LuneOS

meta-luneos/recipes-webos/nyx-conf/nyx-conf/pinephone/nyx.conf
=> nyx-conf: pinephone fix power key path

meta-luneos/recipes-webos/chromium/files/0041-DesktopNativeWidgetAura-donc-apply-DIP-for-SetBounds.patch, meta-luneos/recipes-webos/chromium/webruntime-repo_91.inc, meta-luneos/recipes-webos/configd-data/configd-data.bb, meta-luneos/recipes-webos/wam/wam.bb
This patch a bit hacky, but the current management of the "device scale ratio" in Chromium/Wayland is quite unclear wether the scaling is applied to the web content, or to the wayland window/display. It looks like it is applied to both, which makes it useless for our use-case where cards have a specific size: in this case, the content is scaled up, in a bigger window, which is then scaled down to our card size, so the appearance is identical.
This fix consists mainly in disabling the scaling wayland-side, while keeping it for the web content.
=> webruntime: fix scaling

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0009-com.webos.surfacemanager.perm.json-Add-permissions-f.patch
Fixes: Dec 15 09:39:46 qemux86-64 LunaSysService[472]: [] [pmlog] <default-lib> LS_REQUIRES_SECURITY {"SERVICE":"com.webos.surfacemanager-cardshell","CATEGORY":"/","METHOD":"setPreferences"} Service security groups don't allow method call.
=> luna-surfacemanager: Fix permission issue

meta-luneos/recipes-webos/configurator/configurator.bb, meta-luneos/recipes-webos/configurator/configurator/0004-com.palm.configurator.role.json.in-Add-fixes-for-var.patch, meta-luneos/recipes-webos/core-apps/core-apps.bb, meta-luneos/recipes-webos/sam/sam/0003-com.webos.sam.role.json.in-Fix-various-outbound-perm.patch
Fixes:
2022-12-09T22:31:10.923812Z [4.237099157] kern.warning ls-hubd [] ls-hubd LSHUB_ROLE_FILE {} Can not find service "*" permissions for executable "/usr/sbin/sam"
2022-12-09T22:31:11.633364Z [4.946651635] kern.warning ls-hubd [] ls-hubd LSHUB_ROLE_FILE {} Can not find service "com.palm.imlibpurple" permissions for executable "/usr/sbin/configurator"
2022-12-09T22:31:11.731384Z [5.044671657] kern.warning ls-hubd [] ls-hubd LSHUB_ROLE_FILE {} Can not find service "com.palm.service.contacts" permissions for executable "/usr/sbin/configurator"
2022-12-09T22:31:11.732398Z [5.045685809] kern.warning ls-hubd [] ls-hubd LSHUB_ROLE_FILE {} Can not find service "org.webosports.service.messaging" permissions for executable "/usr/sbin/configurator"
2022-12-09T22:31:11.733725Z [5.047012721] …
=> meta-webos-ports: Fix various permission issues

meta-luneos/recipes-connectivity/connman/connman-conf.bbappend, meta-luneos/recipes-connectivity/connman/connman-conf/connman.service, meta-luneos/recipes-connectivity/connman/connman-conf/connman.sh.in, meta-luneos/recipes-connectivity/connman/connman-conf/environment.conf, meta-luneos/recipes-connectivity/connman/connman-conf/main.conf, meta-luneos/recipes-connectivity/connman/connman/0001-Add-Changes-for-p2p-setState-api.patch, meta-luneos/recipes-connectivity/connman/connman/0002-Add-Changes-for-p2p-getDeviceName-api.patch, meta-luneos/recipes-connectivity/connman/connman/0003-Add-Changes-for-p2p-addService-setwifidisplayinfo-fi.patch, meta-luneos/recipes-connectivity/connman/connman/0004-Add-Changes-for-tethering-setState-api.patch, meta-luneos/recipes-connectivity/connman/connman/0005-Add-Changes-for-p2p-create-group-api.patch, meta-luneos/recipes-connectivity/connman/connman/0006-Add-Changes-for-No-Internet-issue-connman.patch, meta-luneos/recipes-connectivity/connman/connman/0007-Fix-for-create-group-api-and-crash-issue.patch, meta-luneos/recipes-connectivity/connman/connman/0008-Revert-Fix-for-create-group-api-and-crash-issue.patch, meta-luneos/recipes-connectivity/connman/connman/0009-Fix-for-Create-Group-api-and-crash-issue.patch, meta-luneos/recipes-connectivity/connman/connman/0010-Fix-for-peer-Device-List-Info-issue.patch, meta-luneos/recipes-connectivity/connman/connman/0011-Avoid-crash-if-no-interface-found.patch, meta-luneos/recipes-connectivity/connman/connman_%.bbappend, meta-luneos/recipes-connectivity/wpa-supplicant/wpa-supplicant/0001-Add-p2p-changes.patch, meta-luneos/recipes-connectivity/wpa-supplicant/wpa-supplicant/wpa-supplicant.service, meta-luneos/recipes-connectivity/wpa-supplicant/wpa-supplicant/wpa-supplicant.sh, meta-luneos/recipes-connectivity/wpa-supplicant/wpa-supplicant_%.bbappend, meta-luneos/recipes-core/systemd/systemd_%.bbappend, meta-luneos/recipes-webos/webos-connman-adapter/wca-support-api.bb, meta-luneos/recipes-webos/webos-connman-adapter/wca-support-api/0001-Revert-Removing-support-for-com.webos.service.wan-se.patch, meta-luneos/recipes-webos/webos-connman-adapter/wca-support.bb, meta-luneos/recipes-webos/webos-connman-adapter/wca-support/0001-Revert-Removing-support-for-com.webos.service.wan-se.patch, meta-luneos/recipes-webos/webos-connman-adapter/webos-connman-adapter.bb, meta-luneos/recipes-webos/webos-connman-adapter/webos-connman-adapter/0001-Workaround-to-prevent-luna-call-pending.patch, meta-luneos/recipes-webos/webos-connman-adapter/webos-connman-adapter/0002-Add-systemd-service-file.patch, meta-luneos/recipes-webos/webos-connman-adapter/webos-connman-adapter/0003-Add-back-com.palm.wan-for-cellular-support.patch
Move to webos-connman-adapter, wca-supplicant, connman, connman-conf from webOS OSE since they provide more funcitionality in terms of WiFi, tethering etc.
I removed cdc_ether (3G/4G dongles for WAN) from ConnMan since we don't really need that by the looks of it.
https://github.com/webosose/webos-initscripts/blob/master/rootfs/lib/systemd/system/scripts/webos-connman-adapter.sh.in
Only thing really missing is the handling of the cellular interface in webos-connman-adapter.
We'd need to see which approach we'd want to add there:
I.e. (partially revert) https://github.com/webosose/webos-connman-adapter/commit/1babacfd9743f473ead6cb4c895826df5f476791 or forward port the patch we had:
https://github.com/webOS-ports/webos-connman-adapter/commit/d1841e9b681b228a7a89ef68c2949db4f1b4b92d …
=> webos-connman-adapter, wca-supplicant, connman: Move to OSE versions

meta-luneos/classes/webos_app_generate_security_files.bbclass
Legacy apps don't behave nicely due to new "proxied" LS2 calls.
Causes issues like:
Dec 16 10:16:09 qemux86-64 sam[600]: [] [pmlog] <default-lib> LS_REQUIRES_SECURITY {"SERVICE":"com.palm.app.calendar_com.webos.service.activitymanager_proxy","CATEGORY":"/","METHOD":"launch"} Service security groups don't allow method call.
Therefore add 2 variants in the generated file.
=> webos_app_generate_security_files.bbclass: Add fix for legacy apps

meta-luneos/recipes-webos/sam/sam.bb, meta-luneos/recipes-webos/sam/sam/0001-CMakeLists.txt-use-libproc2-from-procps-4.patch, meta-luneos/recipes-webos/sam/sam/0002-sam-remove-procps-dependency.patch, meta-luneos/recipes-webos/sam/sam/0011-NativeContainer-configure-native-apps.patch
Doesn't seem to be needed and would require to be changed for mickledore builds, so better to remove it completely from all 3 active branches.
=> sam: remove procps dependency

meta-luneos/recipes-qt/qt6/qtwayland/0004-QWaylandDisplay-don-t-ignore-wayland-QT_IM_MODULE.patch, meta-luneos/recipes-qt/qt6/qtwayland_git.bbappend
webOS-OSE uses the "wayland" key name for its specific inputcontext plugin, confusing Qt about whether it is a specific request or not.
Ideally the plugin should use another key like wayland-webos, but that would have a much larger impact.
=> qtwayland: fix virtual keyboard not showing up for Qt apps

meta-luneos/recipes-connectivity/ofono/phonesim/0001-Phonesim-Port-to-CMake-and-Qt6.patch, meta-luneos/recipes-connectivity/ofono/phonesim/0002-default.xml-LuneOS-Branding.patch, meta-luneos/recipes-connectivity/ofono/phonesim_git.bb
Upstream finally merged the Qt5 changes after many years, Qt6 still pending, so doing those via a patch.
Provide T-LuneOS instead of T-MeeGo as provider ;)
=> phonesim: Switch to upstream & add Qt6 + branding patches

meta-luneos/conf/distro/include/luneos-preferred-providers.inc
After the OSE rebase, seems I overlooked this and it got broken, let's bring it back. Otherwise we cannot get wifi stuff to work properly on our Android targets and PT2.
=> luneos-preferred-provides.inc: Fix the systemd-machine-units

meta-luneos-backports/meta-luneos-backports-4.3/conf/layer.conf, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/files/0001-gallium-Fix-build-with-llvm-17.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/files/0001-meson-Disable-cmake-dependency-detector-for-llvm.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/files/0001-meson-misdetects-64bit-atomics-on-mips-clang.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/files/0001-meson.build-check-for-all-linux-host_os-combinations.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/libglu_9.0.3.bb, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/mesa-demos/0001-mesa-demos-Add-missing-data-files.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/mesa-demos/0004-Use-DEMOS_DATA_DIR-to-locate-data-files.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/mesa-demos_8.5.0.bb, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/mesa-gl_23.2.1.bb, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/mesa.inc, meta-luneos-backports/meta-luneos-backports-4.3/recipes-graphics/mesa/mesa_23.2.1.bb, meta-luneos-backports/meta-luneos-backports-4.3/recipes-navigation/geoclue/geoclue/0001-Use-google-as-default-and-add-api-key.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-navigation/geoclue/geoclue/0001-libgeoclue-don-t-try-to-use-g-ir-scanner-when-intros.patch, meta-luneos-backports/meta-luneos-backports-4.3/recipes-navigation/geoclue/geoclue_%.bbappend, meta-luneos-backports/meta-luneos-backports-4.3/recipes-navigation/geoclue/geoclue_2.7.1.bb, meta-luneos/conf/layer.conf
To fix issues with Geoclue 2.5.7 on all targets and Mesa with rk3399 (PPP) specifically.
@shr-project Not sure I'm doing it correctly like this? And need to add it to webos-ports-setup too right to enable the layer?
=> Add meta-luneos-backports-4.3: Add newer geoclue and mesa

meta-luneos/recipes-support/sensorfw/sensorfw.bbappend, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-hammerhead.conf, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-tenderloin-halium.conf, meta-luneos/recipes-support/sensorfw/sensorfw/sensord-tenderloin.conf
This bbappend was split from the main bb recipe in order to better separate the setup specific to meta-smartphone devices. It was put initially in meta-smartphone, but the layers configuration doesn't actually allow this.
Bring back this bbappend in meta-webos-ports and keep it separate, so that we can devise later if there is a better place to put this.
=> sensorfw: bring back custom setup for Halium devices

meta-luneos/recipes-support/sensorfw/sensorfw.bbappend
=> sensorfw.bbappend: Use binder for sensorfw on mido-halium.

meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-graphics/sdl2-opengles-test/sdl2-opengles-test/org.mer.app.sdl2_opengles1_test-appinfo.json, meta-luneos/recipes-graphics/sdl2-opengles-test/sdl2-opengles-test/org.mer.app.sdl2_opengles2_test-appinfo.json, meta-luneos/recipes-graphics/sdl2-opengles-test/sdl2-opengles-test_git.bb, meta-luneos/recipes-luneos/apps/org.mer.app.fingerterm.bb, meta-luneos/recipes-luneos/apps/org.mer.app.fingerterm/appinfo.json, meta-luneos/recipes-luneos/apps/org.webosports.app.messwerk.bb
Not having proper appId's can cause havoc when intalling apps with Preware for example. Also LSM seems to be a bit more strict with appIds so let's define proper ones for the apps we ported from elsewhere.
=> meta-webos-ports: Make sure all apps have a proper appId

meta-luneos/recipes-webos/chromium/files/0010-app_shell-override-default-OnWindowHostClose-to-clos.patch, meta-luneos/recipes-webos/chromium/webruntime-repo_94.inc
When Close is called on the Wayland app_shell (i.e. browser) window, it calls the PlatformWindowDelegate::OnWindowHostClose method.
However, by default, this method isn't implemented in Aura's platform window code, because closing a window doesn't always mean closing the app.
As this default code is only called in the browser's context, and not in WAM, implement it to close the whole app.
=> webruntime: fix app_shell (browser) close request

meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager.bb, meta-luneos/recipes-webos/luna-surfacemanager/luna-surfacemanager/0012-WebOSSurfaceItem-close-Wayland-client-fallback-on-Cl.patch, meta-luneos/recipes-webos/maliit-framework-webos/files/maliit-server.path, meta-luneos/recipes-webos/maliit-framework-webos/maliit-framework-webos.bb, meta-luneos/recipes-webos/qml-webos-framework/qml-webos-framework.bb, meta-luneos/recipes-webos/qml-webos-framework/qml-webos-framework/0009-WebOSQuickWindow-use-APP_ID-env-variable-for-appId.patch
Fix two things:
* maliit-server.path triggers maliit-server.service when lsm-ready file is present. However, as LSM depends on maliit-server, it means we'll never be able to stop the surface-manager service. In addition, maliit-server's startup is already triggered by surface-manager.service, so it's useless.
* having maliit-server@.service in SYSTEMD_SERVICE will insert it in the postrm scripts of the package. However, this is a template service, so it's incorrect. Similarly, starting it at startup is incorrect as the instance argument is mandatory. So just remove it, maliit-server@0.service will be started by maliit-server.service anyway.
=> maliit-framework-webos and other fixes

meta-luneos/recipes-webos/nyx-modules/nyx-modules.bb, meta-luneos/recipes-webos/nyx-modules/nyx-modules/0010-nyx-modules-Use-etc-machine-id-for-serial-number.patch
Fixes: Nov 30 10:02:49 pinephonepro nyx-cmd[310]: [] [pmlog] <default-lib> NYXDEV_DEVICEID_OPEN_ERR {} Error in Opening File : /sys/devices/soc0/serial_number
=> nyx-modules: Use alternative for serial number

meta-luneos/recipes-navigation/com.webos.service.location/com.webos.service.location.bb, meta-luneos/recipes-navigation/com.webos.service.location/com.webos.service.location/0007-com.webos.service.location-Remove-gpsConfig-file.patch, meta-luneos/recipes-webos/nyx-conf/nyx-conf.bb, meta-luneos/recipes-webos/nyx-conf/nyx-conf/gpsConfig.conf, meta-luneos/recipes-webos/nyx-conf/nyx-conf/pinephone/gpsConfig.conf, meta-luneos/recipes-webos/nyx-conf/nyx-conf/pinephonepro/gpsConfig.conf, meta-luneos/recipes-webos/webos-connman-adapter/webos-connman-adapter/0003-Update-webos-connman-adapter.role.json.in-Add-permis.patch
We need a device specific configuration file for GPS, instead of having it provided by com.webos.service.location, have it provided by nyx-conf which is any way MACHINE_ARCH already.
=> nyx-conf: Add gpsConfig.conf

meta-luneos/recipes-support/waydroid/waydroid.bb, meta-luneos/recipes-support/waydroid/waydroid/waydroid-container.service, meta-luneos/recipes-support/waydroid/waydroid/waydroid-init.service
Let bitbake take care of the systemd service files, instead of Makefile. This way we can more easily enable it to auto-start.
=> waydroid: Install systemd service files by recipe

meta-luneos/recipes-luneos/nyx-modules-hybris/nyx-modules-hybris.bb
After moving the nyx-modules-hybris recipe, we need to update the FILESEXTRAPATHS:prepend to point to the correct location of nyx-modules.
=> nyx-modules-hybris: Fix FILESEXTRAPATHS:prepend

meta-luneos/recipes-kernel/linux/linux-yocto/waydroid-anbox.cfg
Previous changes lead to some warnings in do_kernel_configcheck due to duplication and comments. Fixes:
[INFO]: Fragments with duplicated configuration options:
- fragment configs/v5.15/standard/./waydroid-anbox.cfg has a duplicated option: CONFIG_NETFILTER_XT_TARGET_CHECKSUM
- fragment configs/v5.15/standard/./waydroid-anbox.cfg has a duplicated option: CONFIG_NETFILTER_XT_MATCH_ADDRTYPE
- fragment configs/v5.15/standard/./waydroid-anbox.cfg has a duplicated option: CONFIG_NETFILTER_XT_MATCH_IPVS
- fragment configs/v5.15/standard/./waydroid-anbox.cfg has a duplicated option: CONFIG_XDP_SOCKETS
- fragment configs/v5.15/standard/./waydroid-anbox.cfg has a duplicated option: CONFIG_BPF_STREAM_PARSER
[INFO]: the following symbols were not found in the active configuration:
- …
=> waydroid-android.cfg: Silence do_kernel_configcheck

meta-luneos/recipes-support/sensorfw/sensorfw.bb, meta-luneos/recipes-support/sensorfw/sensorfw/0001-sensorfwd-Add-TimeoutStopSec-to-improve-shutdown.patch, meta-luneos/recipes-webos-ose/sam/sam/sam.service
To force the service to shut down after 5 seconds instead of waiting the default 90 seconds. This reduces the shutdown/reboot time to 10s from 90s.
=> sensorfw, sam: Add TimeoutStopSec to systemd service files

meta-luneos/recipes-webos-ose/wam/wam/0005-DeviceInfoImpl-add-tvDeviceInfo-data.patch
Parse /etc/buildinfo and use MACHINE and DISTRO_VERSION to populate PalmSystem.deviceInfo
=> wam: fix deviceInfo content

meta-luneos/recipes-webos-ose/wam/wam/0001-security_policy.conf-Add-usr-palm-applications.patch
Apps installed via Preware will be in /media/cryptos/apps/usr/palm/applications.
Whitelist this path, so icons etc will render properly in Preware while listing them.
It will probably also fix unintended issues during the runtime of the apps themselves too.
=> wam: Update patch

meta-luneos/recipes-webos-ose/chromium/files/0001-avoid-link-latomic-failure-on-CentOS-8-host.patch, meta-luneos/recipes-webos-ose/chromium/files/0002-Fix-build-with-gcc-13.patch, meta-luneos/recipes-webos-ose/chromium/files/0003-Fix-build-with-dcheck_always_on-true-in-GN_ARGS.patch, meta-luneos/recipes-webos-ose/chromium/files/0004-neva-Fix-build-with-dcheck_always_on-true-in-GN_ARGS.patch, meta-luneos/recipes-webos-ose/chromium/webruntime-repo_108.inc, meta-luneos/recipes-webos-ose/chromium/webruntime.inc
Enabling libpci causes weird runtime issues with LSM (black screen on OSE, no windows for webapps on LuneOS) on qemux86-64.
=> webruntime.inc: Disable libpci

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-pulsecore-private-headers_17.0.bb
* follow pulseaudio recipe upgrade: https://git.openembedded.org/openembedded-core/commit/meta/recipes-multimedia/pulseaudio?id=123c75bd87330a81ba5b929c35ae34710ddcc449
* fixes pulseaudio-modules-droid failure:
|/home/amelia/devel/webos-ports-env/webos-ports/tmp-glibc/work/sargo-webos-linux/pulseaudio-modules-droid/15.0.88+git/recipe-sysroot-native/usr/bin/aarch64-webos-linux/../../libexec/aarch64-webos-linux/gcc/aarch64-webos-linux/13.2.0/ld: cannot find -lpulsecommon-16.1: No such file or directory
|collect2: error: ld returned 1 exit status
=> pulseaudio-pulsecore-private-headers: upgrade to 17.0

meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid-hidl_git.bb, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio-modules-droid_git.bb, meta-luneui/recipes-webos-ose/luna-service2/luna-service2.bb, meta-luneui/recipes-webos-ose/luna-service2/luna-service2/0007-_LSCheckProvidedTrustedGroups-reduce-log-noise.patch
With scarthgap the PulseAudio 17.0 modules directory is now /usr/lib/pulseaudio/modules.
=> pulseaudio-modules-droid*: fix install directory

meta-luneos/recipes-qt/qt6/qtsensors-sensorfw-plugin_git.bb
Since this is mostly used for Qt6 now :)
=> qtsensors-sensorfw-plugin: Switch to CMake instead of qmake

meta-luneos/recipes-connectivity/wpa-supplicant/wpa-supplicant_%.bbappend, meta-luneos/recipes-core/base-passwd/base-passwd/0001-base-passwd-Update-gid-for-input-and-audio-so-they-m.patch, meta-luneos/recipes-core/base-passwd/base-passwd_%.bbappend, meta-luneos/recipes-core/dbus/dbus_%.bbappend, meta-luneos/recipes-core/images/luneos-image.inc, meta-luneos/recipes-core/packagegroups/packagegroup-luneos-extended.bb, meta-luneos/recipes-core/webos-users-groups/webos-users-groups_1.0.bb, meta-luneos/recipes-extended/shadow/shadow-sysroot/login.defs_shadow-sysroot, meta-luneos/recipes-extended/shadow/shadow-sysroot_%.bbappend, meta-luneos/recipes-luneos/services/org.webosports.service.devmode.bb, meta-luneos/recipes-multimedia/com.webos.service.mediaindexer/com.webos.service.mediaindexer.bb, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend, meta-luneos/recipes-webos-ose/bluetooth/com.webos.service.bluetooth2.bb, meta-luneos/recipes-webos-ose/com.webos.service.camera/com.webos.service.camera.bb, meta-luneos/recipes-webos-ose/com.webos.service.pdm/com.webos.service.pdm.bb, meta-luneos/recipes-webos-ose/wam/wam.inc
To finally get rid of the 2013 version of base-passwd from OSE.
Let recipes create the users/group and add permissions where they need it instead, so it's clear where they originate from.
Only create the system gid/uid and netdev gid hardcoded.
=> base-passwd: Bring us into 2024

meta-luneos/recipes-webos-ose/sam/sam/0001-com.webos.sam.role.json.in-Fix-various-outbound-perm.patch, meta-luneos/recipes-webos-ose/wam/wam/0002-ls2-Add-required-bits-for-LuneOS.patch
Seems that OSE forgot to update their LS2 files after retiring com.webos.memorymanager legacy APIs with with https://github.com/webosose/com.webos.service.memorymanager/commit/c13f55d4c456b5b6006e6ef31c11ba40e698c974
=> Fix outbound permission calls to com.webos.service.memorymanager

meta-luneos/recipes-core/dbus/dbus_%.bbappend, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio/0006-alsa-ucm-Check-UCM-verb.patch, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio/0007-alsa-ucm-Replace-port-device-UCM-context-assertion.patch, meta-luneos/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Fixes: E: [pulseaudio] alsa-ucm.c: Assertion 'dev == data->device' failed at /usr/src/debug/pulseaudio/17.0/src/modules/alsa/alsa-ucm.c:1562, function pa_alsa_ucm_set_port(). Aborting.
=> fix UCM loading with pulseaudio and fix dbus for voicecall

meta-luneos/recipes-luneos/services/org.webosports.service.ipkg.bb
These somehow got broken after our initscripts or scarthgap migrations.
This brings back the feeds.
* Remove the arch.conf file, since it doesn't seem used by Preware (grep on image doesn't find any reference except for skipping it in the code).
* Disable the Macaw-Enyo feed since this doesn't seem to be working (for a while already)
=> org.webosports.service.ipkg: Fix Preware feeds

meta-luneos/recipes-devtools/python/python3-jsonschema_4.17.3.bb
python3-dtschema doesn't support yet python3-jsonschema with versions 4.18+, therefore the DTB checker of the kernel is broken as-is in scarthgap.
To fix that in LuneOS, add python3-jsonschema_4.17.3.bb in meta-webos-ports.
See also https://github.com/devicetree-org/dt-schema/issues/108
=> python3-jsonschema: use version 4.17.3

meta-luneos/conf/distro/include/luneos.inc
There are still many recipes where armv7a isn't properly handled. For instance, bootd and configd still use 32bit printf when using time_t structures in their logs, which can lead to crashes.
=> conf:distro:luneos.inc: disable time64_t on armv7a

meta-luneos/recipes-webos-owo/luna-sysmgr-conf/luna-sysmgr-conf/hammerhead/luna-platform.conf
The ALS iio sensor isn't correctly handled by sensorfw for now, so disable ALS on hammerhead to avoid getting a dark screen all the time.
=> luna-sysmgr-conf:hammerhead: disable ALS

meta-luneos/recipes-webos-ose/chromium/files/0001-Halium-Disable-DRI-build.patch, meta-luneos/recipes-webos-ose/chromium/webruntime-repo_120.inc
On the Halium build, no DRI is available
=> webruntime: add Halium specific patch for DRI
